version: 1.0.{build}
configuration: Release
platform: Any CPU
build:
  project: ProtoZBuffer.sln
  verbosity: minimal
test_script:
 - nuget.exe install OpenCover -ExcludeVersion
 - OpenCover\tools\OpenCover.Console.exe -register:user -filter:"+[ProtoZBuffer]*   -[ProtoZBuffer]ProtoZBuffer.Properties.*" -target:"nunit3-console" -targetargs:"ProtoZBuffer.Tests\bin\release\ProtoZBuffer.Tests.dll -noshadow" -returntargetcode -hideskipped:All -output:coverage.xml
 - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
 - pip install codecov
 - codecov -f "coverage.xml"
